BigComputer-Project/FastChat-Software-Arena

fastchat/serve/gradio_block_arena_anony.py

These changes supports the anonymous arena with sandbox function (pygame included).

Sandbox components are added in anonymous arena

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/sandbox/code_runner.py

Support Vue sandbox

---

fastchat/serve/sandbox/code_runner.py

Support Gradio sandbox

---

custom_components/sandboxcomponent/README.md
custom_components/sandboxcomponent/demo/app.py
custom_components/sandboxcomponent/demo/space.py
custom_components/sandboxcomponent/frontend/Index.svelte
custom_components/sandboxcomponent/frontend/gradio.config.js
custom_components/sandboxcomponent/frontend/package-lock.json
custom_components/sandboxcomponent/frontend/package.json
custom_components/sandboxcomponent/frontend/shared/IFrameContainer.svelte
custom_components/sandboxcomponent/frontend/style.css
custom_components/sandboxcomponent/pyproject.toml

Fix minor issues in the sandbox component

---

custom_components/sandboxcomponent/frontend/Index.svelte
custom_components/sandboxcomponent/frontend/shared/IFrameContainer.svelte
custom_components/sandboxcomponent/pyproject.toml
fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

Minor Tweak and Add support for NiceGUI

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

Fix slow response of checkbox

---

fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

Skip sandbox execution when code not changed.

---

.gitignore
fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

Support one-side chat and regenerate for named and anony tab.

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

Fix syntax error for one-side chat.

---

fastchat/serve/sandbox/code_runner.py
pyproject.toml

Code Post-Processing Enhancement

---

fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

Code Execution Enhancement

---

analysis/replicate_traj.py

Add code for data analysis

---

fastchat/serve/sandbox/code_runner.py

Add stderr log collection for background cmd

---

fastchat/serve/gradio_block_arena_vision.py
fastchat/serve/gradio_block_arena_vision_anony.py
fastchat/serve/gradio_web_server.py

Reverts BigComputer-Project/FastChat-Software-Arena#32

Revert "Lgary/support_code_sandbox_for_vision"

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

Add system prompt display

---

pyproject.toml

Fix: update project dependencies

---

fastchat/serve/sandbox/code_runner.py
tests/test_code_runner.py

feat: extract inline pip command

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/gradio_web_server_multi.py

kaixin/Cleaner UI

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_block_arena_vision_anony.py
fastchat/serve/gradio_block_arena_vision_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

fix: update webdoc

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_block_arena_vision_anony.py
fastchat/serve/gradio_block_arena_vision_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

fix: update system setup

---

custom_components/sandboxcomponent/frontend/Index.svelte
fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/gradio_web_server_multi.py

May need recompilation of the sandbox component

kaixin/feat: open sandbox in new page

---

fastchat/serve/sandbox/code_runner.py
tests/test_code_runner.py

fix: add rules to detect vue elements

---

e2b_sandbox_template/e2b.toml
fastchat/serve/sandbox/code_runner.py
fastchat/serve/sandbox/constants.py

fix: rebuild sandbox for react and vue

---

fastchat/serve/sandbox/code_runner.py

fix: unify sandbox setup

---

fastchat/serve/sandbox/code_runner.py
tests/test_code_runner.py

feat: improve js import extraction

---

fastchat/serve/sandbox/code_runner.py

add Mermaid support to code runner documentation

---

fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

fix: add more error collection

---

fastchat/serve/sandbox/code_runner.py
tests/test_code_runner.py

feat: enhance the install extraction w/ versions

---

e2b_sandbox_template/.dockerignore
fastchat/serve/sandbox/code_runner.py
fastchat/serve/sandbox/sandbox_manager.py

Skip installed packages

---

fastchat/serve/sandbox/code_runner.py

fix: increase background timeout

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

enable sandbox by default

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

fix: correct ui display and respawn

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py

fix: disable regenerate after voting

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py

fix: enable send buttons in new rounds

---

fastchat/serve/sandbox/code_runner.py

fix: use correct sandbox when selected

---

fastchat/serve/gradio_block_arena_named.py

fix: prevent return elements warning in clear history

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

fix: enhance prompt design

---

e2b_sandbox_template/container_app/src/App.tsx
e2b_sandbox_template/e2b.Dockerfile
e2b_sandbox_template/e2b.toml
e2b_sandbox_template/html_app/index.html
e2b_sandbox_template/nginx/nginx.conf
e2b_sandbox_template/react_app/src/main.tsx
e2b_sandbox_template/vue_app/src/App.vue
e2b_sandbox_template/vue_app/src/main.ts
fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_block_arena_vision.py
fastchat/serve/gradio_block_arena_vision_anony.py
fastchat/serve/gradio_block_arena_vision_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py
fastchat/serve/sandbox/constants.py
fastchat/serve/sandbox/sandbox_manager.py
fastchat/serve/sandbox/sandbox_telemetry.py
pyproject.toml

1. Support reuse a sandbox inside one session
2. Support telemetry output to Azure
3. Fix some found bugs

Support Sandbox Reuse, Add Telemetry Output to Azure, and Bugfixes

---

.github/workflows/serve_deploy.yml

Add support for manual triggering of the workflow and update the publish profile secret reference.

Update Azure deployment workflow

---

.github/workflows/serve_deploy.yml

Specify the Dockerfile to use during the build process to ensure the correct image is created.

Fix Docker build process

---

fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py

Fix functionality to update the system prompt in the sandbox state and refactor related methods for improved clarity and maintainability.

Fix system prompt update functionality and refactor related methods

---

api_endpoints_serve.json
fastchat/model/model_registry.py
fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_web_server.py

fix: return vals and register models

---

e2b_sandbox_template/e2b.toml
fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/sandbox/code_runner.py
fastchat/serve/sandbox/sandbox_telemetry.py

Add examples for 3 tabs.

---

api_endpoints_serve.json
fastchat/serve/gradio_block_arena_anony.py
fastchat/serve/gradio_block_arena_named.py
fastchat/serve/gradio_block_arena_vision.py
fastchat/serve/gradio_block_arena_vision_anony.py
fastchat/serve/gradio_block_arena_vision_named.py
fastchat/serve/gradio_web_server.py
fastchat/serve/gradio_web_server_multi.py
fastchat/serve/sandbox/code_runner.py
fastchat/serve/sandbox/sandbox_telemetry.py

Support partial vision input
